
# auth config(frontend --> this backend service)
auth:
  token_secret: example-secret-change-me
  token_expire_hour: 720
  users:
    - username: user1
      password: pass1

# aws config(this backend service --> aws services)
aws:
  region_name: ap-northeast-1
  access_key_id: EXAMPLE_ACCESS_KEY_ID
  secret_access_key: EXAMPLE_SECRET_ACCESS_KEY
  dynamodb:
    table_name_prefix: tabCloud
    # endpoint_url: http://localhost:8000  # uncomment for local dynamodb during test

# elasticsearch index config
elasticsearch:
  endpoint_use: local
  local:
    host: 127.0.0.1
    port: 9200
    scheme: http
    index_name: tab_cloud_tab
    number_of_shards: 1

# http server config
server:
  host: 0.0.0.0
  port: 8300
  cors_origin_list: []  # empty list allows any origin
